import { title } from 'process';

export const popularItems = [
  {
    title: 'Free Fire Level-Up Package',
    image: '/freefire-level-pass.jpg',
    href: '/freefire-level-pass',
    badge: 'TRENDING',
    price: '$9.99',
    originalPrice: '$14.99',
    rating: 4.8,
    reviews: 3421,
    deliveryTime: 'Instant',
    inStock: true,
  },
  {
    title: 'TikTok Coins',
    image: '/tiktok-banner.jpg',
    href: '/tiktok-coin',
    badge: 'TRENDING',
    price: '$5.99',
    originalPrice: '$8.99',
    rating: 4.8,
    reviews: 3421,
    deliveryTime: 'Instant',
    inStock: true,
  },
  {
    title: 'Garena Shells(my)',
    image: '/garena-banner.jpg',
    href: '/garena-shell',
    badge: 'TRENDING',
    price: '$5.99',
    originalPrice: '$8.99',
    rating: 4.8,
    reviews: 3421,
    deliveryTime: 'Instant',
    inStock: true,
  },
  {
    title: 'Facebook Followers',
    image: '/facebook.jpg',
    href: '/facebook-followers',
    badge: 'TRENDING',
    price: '$5.99',
    originalPrice: '$8.99',
    rating: 4.8,
    reviews: 3421,
    deliveryTime: 'Instant',
    inStock: true,
  },
  {
    title: 'Youtube Premium',
    image: '/youtube-premium-banner.jpg',
    href: '/youtube-premium',
    badge: 'TRENDING',
    price: '$5.99',
    originalPrice: '$8.99',
    rating: 4.8,
    reviews: 3421,
    deliveryTime: 'Instant',
    inStock: true,
  },
  {
    title: 'Poppo Live Coins',
    image: '/poppo-banner.jpg',
    href: '/poppo',
    badge: 'TRENDING',
    price: '$5.99',
    originalPrice: '$8.99',
    rating: 4.8,
    reviews: 3421,
    deliveryTime: 'Instant',
    inStock: true,
  },
  {
    title: 'Canva Pro',
    image: '/canva-banner.jpg',
    href: '/canva',
    badge: 'TRENDING',
    price: '$5.99',
    originalPrice: '$8.99',
    rating: 4.8,
    reviews: 3421,
    deliveryTime: 'Instant',
    inStock: true,
  },
  {
    title: 'Paypal Balance Load',
    image: '/paypal-logo.jpg',
    href: '/paypal',
    badge: 'TRENDING',
    price: '$5.99',
    originalPrice: '$8.99',
    rating: 4.8,
    reviews: 3421,
  },
  {
    title: 'Skrill Balance Load',
    image: '/skrill-logo.jpg',
    href: '/skrill',
    badge: 'TRENDING',
    price: '$5.99',
    originalPrice: '$8.99',
    rating: 4.8,
    reviews: 3421,
    deliveryTime: 'Instant',
    inStock: true,
  },
  {
    title: 'CHAT GPT PLUS ( 1 MONTH )',
    image: '/chatgpt-plus-banner.jpg',
    href: '/chatgpt-plus',
    badge: 'TRENDING',
    price: '$700',
    originalPrice: '$700',
    rating: 4.8,
    reviews: 3421,
    deliveryTime: 'Instant',
    inStock: true,
  },
  {
    title: 'CHAT GPT PLUS ( 1 Year )',
    image: '/chatgpt-plus-one-year-banner.jpg',
    href: '/chatgpt-plus-one-year',
    badge: 'TRENDING',
    price: '$7500',
    originalPrice: '$7500',
    rating: 4.8,
  },
  {
    title: 'Perplexity AI Pro (1 Year)',
    image: '/perplexity.jpg',
    href: '/perplexity',
    badge: 'TRENDING',
    price: '$1600',
    originalPrice: '$1600',
    rating: 4.8,
  },
  {
    title: 'Prime Video 4K HD Subscription (5 Device Access)',
    image: '/prime-video.jpg',
    href: '/prime-video',
    badge: 'TRENDING',
    price: '$99',
    originalPrice: '$99',
  },
  {
    title: 'Netflix 4K HD - 1 Month',
    image: '/netflix-4k.jpg',
    href: '/netflix-4k-hd',
    badge: 'TRENDING',
    price: '$140',
    originalPrice: '$140',
    rating: 4.8,
  },
  {
    title: 'Adobe Creative Cloud (1 Year)',
    image: '/adobe-creative-cloud.jpg',
    href: '/adobe-creative-cloud',
    badge: 'TRENDING',
    price: '$1499',
    originalPrice: '$1499',
    rating: 4.8,
  },
  {
    title: 'Microsoft 365 (1 Year)',
    image: '/microsoft-365.jpg',
    href: '/microsoft-365',
    badge: 'TRENDING',
    price: '$1999',
    originalPrice: '$1999',
    rating: 4.8,
  },
  {
    title: 'Coursera Plus (1 Year)',
    image: '/coursera-plus.jpg',
    href: '/coursera-plus',
    badge: 'TRENDING',
    price: '$8499',
    originalPrice: '$8499',
    rating: 4.8,
  },
  {
    title: 'LinkedIn Premium (1 Year)',
    image: '/linkedin.jpg',
    href: '/linkedin',
    badge: 'TRENDING',
    price: '$11899',
    originalPrice: '$11899',
    rating: 4.8,
  },
  {
    title: 'Figma Professional (1 Year)',
    image: '/figma.jpg',
    href: '/figma',
    badge: 'TRENDING',
    price: '$3399',
    originalPrice: '$3399',
    rating: 4.8,
  },
  {
    title: 'You.com subsscription of 1 Year for NPR',
    image: '/you-logo.jpg',
    href: '/you.com',
    badge: 'TRENDING',
    price: '$5099',
    originalPrice: '$5099',
    rating: 4.8,
  },
  {
    title: 'NordVPN subscription of 1 Year for NPR',
    image: '/nord-vpn.jpg',
    href: '/nord-vpn',
    badge: 'TRENDING',
    price: '$1899',
    originalPrice: '$1899',
  },
  {
    title: 'Instagram Followers',
    image: '/instagram-followers.jpg',
    href: '/instagram-followers',
    badge: 'TRENDING',
    price: '$5.99',
    originalPrice: '$8.99',
    rating: 4.8,
  },
  {
    title: 'Instagram Likes',
    image: '/instagram-likes.jpg',
    href: '/instagram-likes',
    badge: 'TRENDING',
    price: '$5.99',
    originalPrice: '$8.99',
    rating: 4.8,
  },
  {
    title: 'Instagram Views',
    image: '/instagram-views.jpg',
    href: '/instagram-views',
    badge: 'TRENDING',
    price: '$5.99',
    originalPrice: '$8.99',
    rating: 4.8,
  },
  {
    title: 'Facebook Followers',
    image: '/facebook-followers.jpg',
    href: '/facebook-followers',
    badge: 'TRENDING',
    price: '$5.99',
    originalPrice: '$8.99',
    rating: 4.8,
  },
  {
    title: 'Facebook Likes',
    image: '/facebook-likes.jpg',
    href: '/facebook-likes',
    badge: 'TRENDING',
    price: '$5.99',
    originalPrice: '$8.99',
    rating: 4.8,
  },
  {
    title: 'Facebook Views',
    image: '/facebook-views.jpg',
    href: '/facebook-views',
    badge: 'TRENDING',
    price: '$5.99',
    originalPrice: '$8.99',
    rating: 4.8,
  },
  {
    title: 'YouTube Subscribers',
    image: '/youtube-subscriber.jpg',
    href: '/youtube-subscriber',
    badge: 'TRENDING',
    price: '$859',
    originalPrice: '$859',
    rating: 4.8,
  },
  {
    title: 'Tiktok Followers',
    image: '/tiktok-views.jpg',
    href: '/tiktok-followers',
    badge: 'TRENDING',
    price: '$5.99',
    originalPrice: '$8.99',
    rating: 4.8,
    reviews: 3421,
    deliveryTime: 'Instant',
    inStock: true,
  },
  {
    title: 'Tiktok Likes',
    image: '/tiktok-views.jpg',
    href: '/tiktok-likes',
    badge: 'TRENDING',
    price: '$5.99',
    originalPrice: '$8.99',
    rating: 4.8,
    reviews: 3421,
    deliveryTime: 'Instant',
    inStock: true,
  },
  {
    title: 'Tiktok Views',
    image: '/tiktok-views.jpg',
    href: '/tiktok-views',
    badge: 'TRENDING',
    price: '$5.99',
    originalPrice: '$8.99',
    rating: 4.8,
    reviews: 3421,
    deliveryTime: 'Instant',
  },
  {
    title: 'Free Fire Evo Access',
    image: '/free-fire.jpg',
    href: '/freefire-evo-access',
    badge: 'TRENDING',
    price: '$5.99',
    originalPrice: '$8.99',
    rating: 4.8,
    reviews: 3421,
    deliveryTime: 'Instant',
    inStock: true,
  },

  // {
  //   title: 'Free Fire Diamonds',
  //   image: '/free-fire.jpg',
  //   badge: 'TRENDING',
  //   price: '$5.99',
  //   originalPrice: '$8.99',
  //   rating: 4.8,
  //   reviews: 3421,
  //   deliveryTime: 'Instant',
  //   inStock: true,
  // },
  // {
  //   title: 'PUBG UC Credits',
  //   image: '/esports.jpg',
  //   badge: 'POPULAR',
  //   price: '$7.99',
  //   originalPrice: '$11.99',
  //   rating: 4.7,
  //   reviews: 2156,
  //   deliveryTime: 'Instant',
  //   inStock: true,
  // },
  // {
  //   title: 'Gaming Controller Pro',
  //   image: '/gaming-controller.jpg',
  //   badge: 'NEW',
  //   price: '$9.99',
  //   originalPrice: '$13.99',
  //   isPopular: true,
  //   rating: 4.9,
  //   reviews: 1834,
  //   deliveryTime: 'Instant',
  //   inStock: true,
  // },
  // {
  //   title: 'Netflix Premium Access',
  //   image: '/mobile-gaming.jpg',
  //   badge: 'PREMIUM',
  //   price: '$15.99',
  //   originalPrice: '$19.99',
  //   rating: 4.6,
  //   reviews: 987,
  //   deliveryTime: 'Instant',
  //   inStock: false,
  // },
  // {
  //   title: 'Steam Wallet Code',
  //   image: '/gaming-setup.jpg',
  //   badge: 'VERIFIED',
  //   price: '$10.00',
  //   originalPrice: '$12.00',
  //   rating: 4.8,
  //   reviews: 2743,
  //   deliveryTime: 'Instant',
  //   inStock: true,
  // },
  // {
  //   title: 'Discord Nitro Premium',
  //   image: '/esports.jpg',
  //   badge: 'FEATURED',
  //   price: '$9.99',
  //   originalPrice: '$14.99',
  //   isPopular: true,
  //   rating: 4.7,
  //   reviews: 1567,
  //   deliveryTime: 'Instant',
  //   inStock: true,
  // },
];
